name: Deploy to FTP

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3   

      - name: Install dependencies and build
        run: |
          npm install
          npm run build
      
      - name: Set FTP credentials as environment variables
        run: |
          echo "SERVER_HOST=${{ secrets.SERVER_HOST }}" >> $GITHUB_ENV
          echo "FTP_USERNAME=${{ secrets.FTP_USERNAME }}" >> $GITHUB_ENV
          echo "FTP_PASSWORD=${{ secrets.FTP_PASSWORD }}" >> $GITHUB_ENV

      - name: Deploy via FTP
        uses: SamKirkland/FTP-Deploy-Action@4.3.3
        with:
          server: ${{ env.SERVER_HOST }}
          username: ${{ env.FTP_USERNAME }}
          password: ${{ env.FTP_PASSWORD }}
          local-dir: dist/
          server-dir: /03/
