name: Deploy to FTP

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3   

      - name: Install dependencies and build
        run: |
          npm install
          npm run build

      - name: Deploy via FTP
        uses: SamKirkland/FTP-Deploy-Action@4.3.3
        with:
          server: echo "${{ secrets.SERVER_HOST }}" >> $GITHUB_ENV
          username: echo "${{ secrets.FTP_USERNAME }}" >> $GITHUB_ENV
          password: echo "{{ secrets.FTP_PASSWORD }}" >> $GITHUB_ENV
          local-dir: dist/
          server-dir: /03/
